### ISSUE TITLE
Output predictions are incorrect

### ISSUE THREAD

**Issue by harveyslash** [keplr-io/quiver#36]
I use quiver like this:

classList =['one','two','three']
server.launch(mmodel,classes=classList)

when testing images from the dashboard, the classes outputs are wrong. Most of the time it displays the same class predictions for images from different classes

**Comment by jakebian** [comment]
ping @kretes do you have time to take a look at this issue with code you introduced?

**Comment by kretes** [comment]
@harveyslash could you describe the issue in detail?

e.g. 
attach a screenshot of quiver showing prediction for some image + attach a code and an output showing what is the proper prediction for given image from your model

**Comment by jakebian** [comment]
I was getting this too on a VGG model, [the default function loading images](https://github.com/keplr-io/quiver/blob/master/quiver_engine/util.py#L32) (@kretes you added this) in that case gives something  that doesn't make much sense.  Restored the old default loading function for now.

More generally we should allow passing this preprocessing function as an argument because for example, @kretes the function you added were to fit some other model you were playing with. I'll add that.

This issue should be solved.
